#!/usr/bin/env bash
# Create two isolated FINCLAW_HOME trees, init profiles, install markdown + A2A config.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib.sh
source "$SCRIPT_DIR/lib.sh"

require_finclaw
require_cmd python3
ensure_demo_dirs
common_env

install_markdown() {
  local src_dir="$1"
  local workspace="$2"
  mkdir -p "$workspace"
  for f in IDENTITY.md SOUL.md AGENT.md TOOLS.md; do
    cp "$src_dir/$f" "$workspace/$f"
  done
}

echo "==> Preparing callee home at $CALLEE_HOME"
rm -rf "$CALLEE_HOME"
mkdir -p "$CALLEE_HOME"
(
  export FINCLAW_HOME="$CALLEE_HOME"
  "$FINCLAW_BIN" init --non-interactive >/dev/null
)
install_markdown "$EXAMPLE_ROOT/callee" "$(callee_workspace)"

mkdir -p "$(callee_config_dir)"
# Substitute port into inbound template.
python3 - "$EXAMPLE_ROOT/callee/a2a-inbound.yaml" "$(callee_config_dir)/a2a-inbound.yaml" "$CALLEE_PORT" "$DEMO_TOKEN" "$CALLEE_CARD_NAME" <<'PY'
import pathlib, sys
src, dst, port, token, name = sys.argv[1:6]
text = pathlib.Path(src).read_text(encoding="utf-8")
text = text.replace("28701", port).replace("two-agent-a2a-demo-token", token)
text = text.replace("two-agent-callee", name)
pathlib.Path(dst).write_text(text, encoding="utf-8")
PY

echo "==> Preparing caller home at $CALLER_HOME"
rm -rf "$CALLER_HOME"
mkdir -p "$CALLER_HOME"
(
  export FINCLAW_HOME="$CALLER_HOME"
  "$FINCLAW_BIN" init --non-interactive >/dev/null
)
install_markdown "$EXAMPLE_ROOT/caller" "$(caller_workspace)"

mkdir -p "$(caller_config_dir)"
python3 - "$EXAMPLE_ROOT/caller/a2a-agents.http.yaml" "$(caller_config_dir)/a2a-agents.yaml" "$CALLEE_PORT" "$DEMO_TOKEN" <<'PY'
import pathlib, sys
src, dst, port, token = sys.argv[1:5]
text = pathlib.Path(src).read_text(encoding="utf-8")
text = text.replace("28701", port).replace("two-agent-a2a-demo-token", token)
pathlib.Path(dst).write_text(text, encoding="utf-8")
PY

# Persist env hints for other scripts.
cat >"$DEMO_ROOT/env.sh" <<EOF
# Generated by 00-prepare-homes.sh — source from other scripts.
export TWO_AGENT_DEMO_ROOT=$(printf '%q' "$DEMO_ROOT")
export CALLEE_HOME=$(printf '%q' "$CALLEE_HOME")
export CALLER_HOME=$(printf '%q' "$CALLER_HOME")
export CALLEE_PORT=$(printf '%q' "$CALLEE_PORT")
export DEMO_TOKEN=$(printf '%q' "$DEMO_TOKEN")
export CALLEE_CARD_NAME=$(printf '%q' "$CALLEE_CARD_NAME")
export FINCLAW_BIN=$(printf '%q' "$FINCLAW_BIN")
EOF

echo "OK prepare"
echo "  callee inbound: $(callee_config_dir)/a2a-inbound.yaml"
echo "  caller agents:  $(caller_config_dir)/a2a-agents.yaml"
echo "  demo root:      $DEMO_ROOT"
